### ISSUE TITLE
sorry for contacting you this way ... 

### ISSUE THREAD

**Issue by BreitiDE** [j9brown/camel#1]
hi, i use your victron hacs  integration because it supports inverters and is working well, I fond two issue I can't solve ... the shunt current is showing negative values positive and the external device load on MPPT whows 97A instead of 9.7A ... any idea how to look to solve ... I am more a no pro programmer not much in touch with python,  too poison :) 

hope you can help ... thank you

Current should be -0,94 instead of 0,94
![image](https://github.com/j9brown/camel/assets/24428945/1f73f48d-ad51-435e-bdcf-f7535782b38c)

External device load should be 9,7 instead of 97
![image](https://github.com/j9brown/camel/assets/24428945/2bf184ad-9998-4558-9fa2-eafebaef3093)

**Comment by j9brown** [comment]
Sounds like a bug.  I’ll take a look and I have enabled the issue tracker for my fork of victron-ble.

**Comment by j9brown** [comment]
I have fixed the bug and several related issues.  Please try the latest release and let me know whether it solved the problem.  Thanks for reporting it!

**Comment by BreitiDE** [comment]
hey, tested and works so far, values for device load on MPPT and negative current on shunt now shown ... thank you very much ... we do not need to track this issue on veicton hacs .. right. ? I will do more tests this the next two weeks and come back to the viictron-hacs/issue if I found one :) Thank you !
